solve dependency conflict around lair_keystore_api
the following error showed up with `cargo publish --dry-run`:

```
kitsune_p2p_proxy:     Updating crates.io index
 Packaging kitsune_p2p_proxy v0.0.2 (/home/steveej/src/holo/holochain/crates/kitsune_p2p/proxy)
 Archiving CHANGELOG.md
 Archiving Cargo.lock
error: failed to prepare local package for uploading

Caused by:
failed to select a version for `lair_keystore_api`.
    ... required by package `kitsune_p2p_transport_quic v0.0.2`
    ... which is depended on by `kitsune_p2p_proxy v0.0.2 (/home/steveej/src/holo/holochain/crates/kitsune_p2p/proxy)`
versions that meet the requirements `=0.0.1-alpha.12` are: 0.0.1-alpha.12

all possible versions conflict with previously selected packages.

  previously selected package `lair_keystore_api v0.0.1-alpha.13`
    ... which is depended on by `kitsune_p2p_proxy v0.0.2 (/home/steveej/src/holo/holochain/crates/kitsune_p2p/proxy)`

   failed to select a version for `lair_keystore_api` which could resolve this conflict
```